#include "main.h"

/* LIMITS FOR PWM OF MOTOR MOVEMENT*/
#define MMOVEMENTON 500
#define MMOVEMENTOFF 1000

/* LIMITS FOR PWM OF MOTOR DIRECTION*/
#define MDIRECTIONDOWN 250
#define MDIRECTIONUP 750
#define MDIRECTIONOFF 1000
