#include "main.h"

/* LIMITS FOR PWM OF MOTOR MOVEMENT*/
#define MMOVEMENTON 500
#define MMOVEMENTOFF 1000

/* LIMITS FOR PWM OF MOTOR DIRECTION*/
#define MDIRECTIONDOWN 750
#define MDIRECTIONUP 250
#define MDIRECTIONOFF 1000
#define AVOIDERROR1 500
#define AVOIDERROR2 750

/* LIMITS FOR PWM OF SERVO*/
#define SERVO0ON 10
#define SERVO0OFF 20
#define SERVO180ON 20
#define SERVO180OFF 40

/*Functions*/
void ServoON(void);
void setFlag(void);